[package]
name = "giftwrap"
version = "0.1.0"
edition = "2024"

[package.metadata.giftwrap]
default_target = "x86_64-unknown-linux-musl"

[dependencies]
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shell-words = "1.1"
sha1 = "0.10"
tar = "0.4"
toml = "0.8"

[dev-dependencies]
tempfile = "3"
